import json
from pathlib import Path

def create_contract(filename, c_id, t_id, title, raw_clauses, contradictions, traps=[]):
    clauses = []
    contract_text = ""
    for c in raw_clauses:
        clauses.append({"id": c["id"], "title": c["title"], "text": c["text"]})
        contract_text += f"{c['title']}\n{c['text']}\n\n"
    data = {
        "contract_id": c_id, "task_id": t_id, "title": title,
        "contract_text": contract_text.strip(),
        "clauses": clauses, "contradictions": contradictions, "traps": traps
    }
    out_dir = Path("data/contracts")
    out_dir.mkdir(parents=True, exist_ok=True)
    with open(out_dir / filename, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)

def build_easy_001():
    c = [
        {"id": "clause_01", "title": "Parties", "text": "This Non-Disclosure Agreement (\"Agreement\") is entered into as of the date last signed below by and between Acme Corp, a Delaware corporation with its principal offices at 100 Innovation Drive, Wilmington, DE 19801 (\"Disclosing Party\"), and Beta Ltd, a company incorporated in England and Wales with its registered office at 45 Kensington High Street, London W8 5NP (\"Receiving Party\")."},
        {"id": "clause_02", "title": "Purpose", "text": "The parties wish to explore a potential business relationship (the \"Purpose\") in connection with which the Disclosing Party may disclose to the Receiving Party certain proprietary and confidential information relating to its products, technology, business plans, financial data, and strategic initiatives."},
        {"id": "clause_03", "title": "Confidentiality Period", "text": "The Receiving Party shall maintain the confidentiality of all Confidential Information disclosed under this Agreement for a period of two (2) years from the date of each such disclosure, after which the obligations of confidentiality shall expire."},
        {"id": "clause_04", "title": "Permitted Disclosures", "text": "The Receiving Party may disclose Confidential Information only to its directors, officers, employees, and professional advisors who have a bona fide need to know such information for the Purpose and who are bound by written obligations of confidentiality no less restrictive than those contained herein."},
        {"id": "clause_05", "title": "Exclusions from Confidentiality", "text": "Confidential Information shall not include information that: (a) is or becomes publicly available through no fault or action of the Receiving Party; (b) was already in the Receiving Party's possession prior to disclosure; (c) is independently developed by the Receiving Party without use of or reference to the Confidential Information; or (d) is received from a third party who is not under any obligation of confidentiality with respect to such information."},
        {"id": "clause_06", "title": "Return or Destruction of Information", "text": "Upon the earlier of (i) termination of this Agreement or (ii) written request by the Disclosing Party, the Receiving Party shall promptly return or destroy all tangible materials containing Confidential Information and shall certify in writing that it has done so within fifteen (15) business days."},
        {"id": "clause_07", "title": "Obligations Upon Termination", "text": "Upon termination of this Agreement for any reason, all confidentiality obligations set forth herein shall remain in full force and effect for a period of thirty-six (36) months from the effective date of termination, during which the Receiving Party shall continue to protect all previously disclosed Confidential Information."},
        {"id": "clause_08", "title": "Governing Law", "text": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, United States of America, without regard to its conflict of laws principles. Any dispute arising out of or in connection with this Agreement shall be submitted to the exclusive jurisdiction of the state and federal courts located in Wilmington, Delaware."},
    ]
    contradictions = [{"clause_a_id": "clause_03", "clause_b_id": "clause_07", "type": "temporal", "description": "Clause 03 states confidentiality lasts 2 years (24 months) from disclosure, but Clause 07 states obligations continue for 36 months from termination — conflicting durations for the same confidentiality obligation."}]
    create_contract("easy_001.json", "easy_001", "easy", "Non-Disclosure Agreement between Acme Corp and Beta Ltd", c, contradictions)

def build_easy_002():
    c = [
        {"id": "clause_01", "title": "Parties and Recitals", "text": "This Service Agreement (\"Agreement\") is entered into by and between GlobalTech Inc, a California corporation with its principal place of business at 2200 Sand Hill Road, Menlo Park, CA 94025 (\"Client\"), and SwiftDeliver Ltd, a limited company registered in Ontario, Canada with offices at 180 Bay Street, Toronto, ON M5J 2T3 (\"Supplier\")."},
        {"id": "clause_02", "title": "Scope of Services", "text": "The Supplier agrees to provide comprehensive logistics, warehousing, and last-mile delivery services to the Client across all North American territories as more particularly described in Schedule A attached hereto. Services shall commence within thirty (30) days of the Effective Date and shall be performed in accordance with all applicable industry standards and regulations."},
        {"id": "clause_03", "title": "Delivery Costs", "text": "The Supplier shall be solely responsible for all shipping, handling, and delivery costs incurred in performing services under this Agreement, including but not limited to freight charges, customs duties, packaging materials, fuel surcharges, and any incidental transportation expenses."},
        {"id": "clause_04", "title": "Payment Terms", "text": "The Client shall pay the Supplier's invoices for service fees (exclusive of shipping and handling costs addressed elsewhere in this Agreement) within thirty (30) days of receipt of a valid and undisputed invoice. All payments shall be made in United States Dollars by electronic funds transfer."},
        {"id": "clause_05", "title": "Insurance Requirements", "text": "The Supplier shall maintain, at its own cost and expense, comprehensive general liability insurance with a minimum coverage of One Million United States Dollars ($1,000,000) per occurrence and Two Million United States Dollars ($2,000,000) in the aggregate, and shall name the Client as an additional insured on all such policies."},
        {"id": "clause_06", "title": "Term of Agreement", "text": "This Agreement shall commence on the Effective Date and shall remain in full force and effect for an initial term of one (1) year, unless earlier terminated in accordance with the provisions of this Agreement."},
        {"id": "clause_07", "title": "Cost Allocation", "text": "All shipping, handling, and logistics costs arising from services provided hereunder shall be borne exclusively by the Client and reimbursed to the Supplier within ten (10) business days of the Supplier's submission of an itemized invoice for such costs."},
        {"id": "clause_08", "title": "Dispute Resolution", "text": "Any dispute, controversy, or claim arising out of or relating to this Agreement shall be resolved through binding arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules. The arbitration shall take place in San Francisco, California, and the decision of the arbitrator shall be final and binding."},
    ]
    contradictions = [{"clause_a_id": "clause_03", "clause_b_id": "clause_07", "type": "party_obligation", "description": "Clause 03 assigns all shipping/handling costs to the Supplier, but Clause 07 assigns the exact same costs exclusively to the Client."}]
    create_contract("easy_002.json", "easy_002", "easy", "Service Agreement between GlobalTech Inc and SwiftDeliver Ltd", c, contradictions)

def build_medium_001():
    c = [
        {"id": "clause_01", "title": "Definitions", "text": "In this SaaS Subscription Agreement between NovaSoft Inc (\"Vendor\") and RetailCo Ltd (\"Customer\"): \"Platform\" means the cloud-based software application; \"Subscription Term\" means the period during which access is granted; \"Authorized Users\" means employees or contractors designated by Customer."},
        {"id": "clause_02", "title": "Scope of Services", "text": "Vendor shall provide Customer with access to the Platform, including all standard features, modules, and integrations as described in the applicable Order Form."},
        {"id": "clause_03", "title": "Implementation and Onboarding", "text": "Vendor shall provide a dedicated implementation manager and complete onboarding within sixty (60) days of the Effective Date, including data migration, user training, and configuration of the Platform to Customer's specifications."},
        {"id": "clause_04", "title": "Payment Terms", "text": "All invoices issued by Vendor are payable within Net 30 days of receipt by the Customer. Customer shall remit payment via wire transfer or ACH to the account specified on each invoice."},
        {"id": "clause_05", "title": "Support and Maintenance SLA", "text": "Vendor shall provide Tier 1 and Tier 2 technical support during business hours (8:00 AM to 6:00 PM Eastern Time, Monday through Friday). Critical severity issues shall receive an initial response within one (1) hour."},
        {"id": "clause_06", "title": "License Grant", "text": "Vendor grants Customer a non-exclusive, worldwide license to use the Platform and its associated documentation for any commercial purpose, including the right to sublicense and resell access to the Platform to Customer's own end users and clients."},
        {"id": "clause_07", "title": "Uptime Guarantee", "text": "Vendor guarantees Platform availability of 99.9% measured on a calendar month basis, excluding scheduled maintenance windows communicated at least 48 hours in advance."},
        {"id": "clause_08", "title": "Data Backup", "text": "Vendor shall maintain automated daily backups of all Customer data stored in the Platform and shall retain such backups for a minimum of thirty (30) days. In the event of data loss, Vendor shall restore Customer data from the most recent available backup at no additional charge."},
        {"id": "clause_09", "title": "Security and Compliance", "text": "Vendor shall maintain SOC 2 Type II certification and comply with all applicable data protection regulations. All Customer data shall be encrypted at rest using AES-256 and in transit using TLS 1.2 or higher."},
        {"id": "clause_10", "title": "Intellectual Property Ownership", "text": "Vendor retains all right, title, and interest in the Platform, including all modifications and derivative works. Customer retains all rights in Customer Data uploaded to or generated within the Platform."},
        {"id": "clause_11", "title": "Use Restrictions", "text": "The license granted hereunder is strictly limited to the Customer's internal business operations. Any resale, sublicensing, redistribution, or provision of access to third parties is expressly prohibited without prior written consent from Vendor."},
        {"id": "clause_12", "title": "Termination for Convenience", "text": "Either party may terminate this Agreement at any time upon providing thirty (30) days written notice to the other party, without the requirement to show cause or provide justification."},
        {"id": "clause_13", "title": "Confidentiality", "text": "Each party agrees to maintain the confidentiality of the other party's proprietary information and shall not disclose such information to any third party without prior written consent."},
        {"id": "clause_14", "title": "Late Payment Penalty", "text": "Any invoice remaining unpaid after forty-five (45) days from the date of receipt shall incur a late payment fee of two percent (2%) per month on the outstanding balance, compounding monthly until paid in full."},
        {"id": "clause_15", "title": "Warranties and Representations", "text": "Vendor warrants that the Platform shall perform substantially in accordance with its published documentation and that Vendor has the legal authority to enter into this Agreement."},
        {"id": "clause_16", "title": "Limitation of Liability", "text": "In no event shall either party's total aggregate liability under this Agreement exceed the total fees paid by Customer during the twelve (12) month period immediately preceding the claim."},
        {"id": "clause_17", "title": "Customer Responsibilities", "text": "Customer is solely and exclusively responsible for maintaining adequate backups of all data uploaded to or generated within the Platform. Vendor assumes no responsibility whatsoever for any data loss, corruption, or unavailability regardless of cause."},
        {"id": "clause_18", "title": "Indemnification", "text": "Each party shall indemnify and hold harmless the other party from any third-party claims arising from the indemnifying party's breach of this Agreement or negligent acts or omissions."},
        {"id": "clause_19", "title": "Force Majeure", "text": "Neither party shall be liable for any failure or delay in performance due to circumstances beyond its reasonable control, including natural disasters, war, pandemic, or government actions."},
        {"id": "clause_20", "title": "Automatic Renewal", "text": "This Agreement shall automatically renew for successive one-year terms unless either party provides written notice of non-renewal no less than ninety (90) days prior to the end of the then-current term."},
        {"id": "clause_21", "title": "Audit Rights", "text": "Vendor shall permit Customer to audit Vendor's compliance with the terms of this Agreement upon thirty (30) days written notice, no more than once per calendar year."},
        {"id": "clause_22", "title": "Notices and Communications", "text": "All notices required under this Agreement shall be in writing and delivered via certified mail, overnight courier, or email to the addresses specified in the Order Form."},
        {"id": "clause_23", "title": "Amendments and Waivers", "text": "No amendment to this Agreement shall be effective unless made in writing and signed by authorized representatives of both parties."},
        {"id": "clause_24", "title": "Governing Law", "text": "This Agreement shall be governed by and construed in accordance with the laws of the State of California, without regard to its conflict of laws provisions."},
        {"id": "clause_25", "title": "Entire Agreement", "text": "This Agreement, including all schedules and exhibits attached hereto, constitutes the entire agreement between the parties and supersedes all prior negotiations, representations, and agreements."},
    ]
    contradictions = [
        {"clause_a_id": "clause_04", "clause_b_id": "clause_14", "type": "numeric", "description": "Payment due Net 30 but late penalty triggers at 45 days, creating a 15-day gap."},
        {"clause_a_id": "clause_06", "clause_b_id": "clause_11", "type": "scope", "description": "License allows resale and sublicensing vs restrictions expressly prohibit resale."},
        {"clause_a_id": "clause_08", "clause_b_id": "clause_17", "type": "party_obligation", "description": "Vendor maintains backups vs Customer solely responsible for backups."},
        {"clause_a_id": "clause_12", "clause_b_id": "clause_20", "type": "termination_renewal", "description": "30-day termination notice vs 90-day non-renewal notice are irreconcilable."},
    ]
    create_contract("medium_001.json", "medium_001", "medium", "SaaS Subscription Agreement between NovaSoft Inc and RetailCo Ltd", c, contradictions)

def build_medium_002():
    c = [
        {"id": "clause_01", "title": "Preamble", "text": "This Professional Services Agreement (\"Agreement\") is entered into between DesignPro Agency, a creative services firm incorporated in New York (\"Service Provider\"), and BuildCorp Ltd, a construction and development company headquartered in Chicago, Illinois (\"Client\")."},
        {"id": "clause_02", "title": "Scope of Work", "text": "Service Provider shall deliver brand identity design, architectural visualization, marketing collateral, and digital strategy consulting services as detailed in the Statement of Work attached as Exhibit A."},
        {"id": "clause_03", "title": "Hourly Rates", "text": "The maximum blended hourly rate for any personnel assigned to the project shall not exceed One Hundred Fifty United States Dollars ($150.00) per hour, inclusive of all overhead and administrative costs."},
        {"id": "clause_04", "title": "Payment Schedule", "text": "Client shall pay thirty percent (30%) of the total project fee upon execution of this Agreement, forty percent (40%) upon delivery of initial concepts, and the remaining thirty percent (30%) upon final approval of all deliverables."},
        {"id": "clause_05", "title": "Intellectual Property Ownership", "text": "Upon full and final payment of all fees and costs, Client shall obtain exclusive, perpetual, irrevocable, worldwide ownership of all copyrights, trademarks, and intellectual property rights in and to the final deliverables created specifically for Client under this Agreement."},
        {"id": "clause_06", "title": "Confidentiality", "text": "Both parties agree to keep strictly confidential all proprietary information, trade secrets, business strategies, and unpublished creative works shared during the term of this Agreement, for a period of three (3) years following termination."},
        {"id": "clause_07", "title": "Warranties", "text": "Service Provider warrants that all deliverables shall be original works of authorship and shall not infringe upon any third-party intellectual property rights."},
        {"id": "clause_08", "title": "Insurance", "text": "Service Provider shall maintain professional liability (errors and omissions) insurance with minimum coverage of One Million United States Dollars ($1,000,000) throughout the duration of this Agreement."},
        {"id": "clause_09", "title": "Senior Staffing Rate", "text": "Client agrees to be billed at a rate of Two Hundred Twenty-Five United States Dollars ($225.00) per hour for all hours worked by senior design directors and principal creative officers assigned to the engagement."},
        {"id": "clause_10", "title": "Travel Expenses", "text": "Service Provider shall be solely responsible for covering all travel, lodging, and meal expenses associated with performing the services under this Agreement, including site visits, client presentations, and industry conferences."},
        {"id": "clause_11", "title": "Term", "text": "This Agreement shall commence on the Effective Date and shall continue for an initial term of twelve (12) months, or until all deliverables have been completed and accepted, whichever occurs later."},
        {"id": "clause_12", "title": "Termination for Cause", "text": "Either party may terminate this Agreement immediately upon written notice if the other party commits a material breach and fails to cure such breach within fifteen (15) business days of receiving written notice specifying the nature of the breach."},
        {"id": "clause_13", "title": "Retained Rights", "text": "Service Provider retains all copyrights, intellectual property rights, and moral rights to the final deliverables produced under this Agreement and grants Client only a limited, non-exclusive, non-transferable license for use in Client's internal business operations."},
        {"id": "clause_14", "title": "Indemnification", "text": "Service Provider shall indemnify and hold harmless Client from and against all claims, damages, losses, and expenses arising from any breach of Service Provider's warranties or negligent acts or omissions."},
        {"id": "clause_15", "title": "Project Extension", "text": "The project timeline may be extended by mutual written agreement of the parties, provided that written notice of the requested extension is given at least fourteen (14) calendar days before the then-scheduled completion date."},
        {"id": "clause_16", "title": "Force Majeure", "text": "Neither party shall be liable for delays or failures in performance resulting from causes beyond its reasonable control, including but not limited to acts of God, natural disasters, epidemics, government orders, labor disputes, or supply chain disruptions."},
        {"id": "clause_17", "title": "Non-Solicitation", "text": "During the term of this Agreement and for twelve (12) months thereafter, neither party shall directly or indirectly solicit or hire any employee or contractor of the other party without prior written consent."},
        {"id": "clause_18", "title": "Reimbursable Costs", "text": "Client agrees to fully reimburse Service Provider for all out-of-pocket travel, lodging, and meal expenses incurred during the performance of services under this Agreement, upon submission of itemized receipts within thirty (30) days."},
        {"id": "clause_19", "title": "Dispute Resolution", "text": "Any dispute arising under this Agreement shall be resolved through mediation administered by JAMS in New York, New York. If mediation fails, the dispute shall proceed to binding arbitration under JAMS Comprehensive Arbitration Rules."},
        {"id": "clause_20", "title": "Limitation of Liability", "text": "In no event shall either party's total liability under this Agreement exceed the total fees actually paid or payable to Service Provider during the twelve (12) months preceding the event giving rise to the claim."},
        {"id": "clause_21", "title": "Subcontracting", "text": "Service Provider may engage qualified subcontractors to perform portions of the services, provided that Service Provider remains fully responsible for the quality and timeliness of all work product."},
        {"id": "clause_22", "title": "Timeline Finality", "text": "Any request to extend the project timeline must be submitted in writing by the requesting party no fewer than forty-five (45) calendar days prior to the original completion date specified in the Statement of Work. Requests submitted after this deadline shall be automatically denied."},
        {"id": "clause_23", "title": "Governing Law", "text": "This Agreement shall be governed by the laws of the State of New York, without regard to its conflict of laws provisions."},
        {"id": "clause_24", "title": "Notices", "text": "All notices under this Agreement shall be in writing and delivered by certified mail, nationally recognized overnight courier, or email with confirmed receipt, to the addresses set forth in the signature block."},
        {"id": "clause_25", "title": "Entire Agreement", "text": "This Agreement, together with all exhibits and schedules, constitutes the entire agreement between the parties and supersedes all prior understandings, negotiations, and agreements, whether written or oral."},
    ]
    contradictions = [
        {"clause_a_id": "clause_03", "clause_b_id": "clause_09", "type": "numeric", "description": "Max blended hourly rate is $150 per hour but senior design directors billed at $225 per hour."},
        {"clause_a_id": "clause_05", "clause_b_id": "clause_13", "type": "scope", "description": "Client gets exclusive IP ownership vs Service Provider retains all IP, granting only limited license."},
        {"clause_a_id": "clause_10", "clause_b_id": "clause_18", "type": "party_obligation", "description": "Provider covers travel expenses vs Client reimburses all travel expenses."},
        {"clause_a_id": "clause_15", "clause_b_id": "clause_22", "type": "temporal", "description": "14-day extension notice required vs 45-day extension notice required."},
    ]
    create_contract("medium_002.json", "medium_002", "medium", "Professional Services Agreement between DesignPro Agency and BuildCorp Ltd", c, contradictions)

def build_hard_001():
    # 60 clauses for Master Service Agreement
    c = []
    for i in range(1, 61):
        c.append({"id": f"clause_{i:02d}", "title": f"General Provision {i}", "text": f"This clause sets forth standard representations, warranties, and obligations typical for enterprise master service agreements between sophisticated commercial parties operating under Delaware law. Both parties acknowledge their respective rights and responsibilities under Section {i} of the applicable regulatory framework."})

    # Named clauses with contradiction/trap content
    c[0] = {"id": "clause_01", "title": "Parties and Recitals", "text": "This Master Service Agreement (\"MSA\") is entered into between Apex Systems Corp, a Delaware corporation (\"Vendor\"), and MegaRetail Group, a multinational retail enterprise headquartered in New York (\"Client\"). The parties wish to establish the terms governing the provision of enterprise technology services."}
    c[1] = {"id": "clause_02", "title": "Definitions", "text": "In this Agreement: \"Business Day\" means any day that is not a Saturday, Sunday, or public holiday in the State of Delaware. \"Confidential Information\" means all non-public information disclosed by one party to the other. \"Deliverables\" means all work product created under a Statement of Work. \"Services\" means the professional, technical, and managed services provided by Vendor."}
    c[2] = {"id": "clause_03", "title": "Scope of Services", "text": "Vendor shall provide the technology consulting, systems integration, managed infrastructure, and application development services described in each Statement of Work executed under this MSA."}
    c[3] = {"id": "clause_04", "title": "Statements of Work", "text": "Each engagement shall be governed by a separate Statement of Work that references this MSA, describes the scope of services, timeline, milestones, and applicable fees."}
    c[4] = {"id": "clause_05", "title": "Payment Terms", "text": "All validated invoices issued by Vendor under any Statement of Work are strictly payable within Net 30 days of receipt by the Client. Late payments shall accrue interest at 1.5% per month."}
    c[5] = {"id": "clause_06", "title": "Personnel and Staffing", "text": "Vendor shall assign qualified personnel with sufficient experience and expertise to perform the services. Client may request replacement of any assigned personnel upon reasonable written notice."}
    c[6] = {"id": "clause_07", "title": "License Grant", "text": "Vendor hereby grants Client a perpetual, worldwide, unrestricted, royalty-free license to use, modify, reproduce, and create derivative works from all Deliverables produced under this Agreement."}
    c[7] = {"id": "clause_08", "title": "Standard Payment", "text": "Standard payment terms for recurring managed services invoices are Net 45 days from the date of invoice."}
    c[8] = {"id": "clause_09", "title": "Limitation of Liability", "text": "Under no circumstances shall Vendor's total aggregate liability arising out of or relating to this Agreement or any Statement of Work exceed Five Hundred Thousand United States Dollars ($500,000)."}
    c[9] = {"id": "clause_10", "title": "Warranties", "text": "Vendor warrants that all Services shall be performed in a professional and workmanlike manner consistent with generally accepted industry standards and practices."}
    c[10] = {"id": "clause_11", "title": "Indemnification by Vendor", "text": "Vendor shall indemnify, defend, and hold harmless Client and its affiliates, officers, directors, and employees from and against any and all third-party claims, damages, losses, costs, and expenses (including reasonable attorney fees) arising from Vendor's negligence or willful misconduct in performing the Services."}
    c[11] = {"id": "clause_12", "title": "Confidentiality", "text": "Each party shall maintain the confidentiality of the other party's Confidential Information using at least the same degree of care it uses to protect its own confidential information, but in no event less than reasonable care."}
    c[12] = {"id": "clause_13", "title": "Audit Rights", "text": "Client is granted the express right to audit Vendor's systems, records, processes, and facilities related to the Services at any time upon providing five (5) Business Days' prior written notice. Vendor shall reasonably cooperate with such audits."}
    c[13] = {"id": "clause_14", "title": "Primary Data Processing", "text": "All primary data processing activities shall occur within facilities physically located in the Territory, defined as the United States of America and Canada."}
    c[14] = {"id": "clause_15", "title": "Data Protection", "text": "Vendor shall comply with all applicable data protection laws including CCPA, GDPR where applicable, and relevant state privacy statutes. All Client personal data shall be encrypted at rest and in transit."}
    c[15] = {"id": "clause_16", "title": "Insurance Requirements", "text": "Vendor shall obtain and maintain comprehensive general liability insurance with minimum coverage of Two Million United States Dollars ($2,000,000) per occurrence and shall name Client as an additional insured on all such policies throughout the term of this Agreement."}
    c[16] = {"id": "clause_17", "title": "Compliance with Laws", "text": "Both parties shall comply with all applicable federal, state, and local laws, regulations, and ordinances in the performance of their obligations under this Agreement."}
    c[17] = {"id": "clause_18", "title": "Intellectual Property Restrictions", "text": "Under no circumstances may Client modify, alter, adapt, reverse engineer, decompile, or create derivative works from any Deliverables, software tools, or proprietary materials provided by Vendor without prior written approval from Vendor."}
    c[18] = {"id": "clause_19", "title": "Non-Solicitation", "text": "During the term and for twelve (12) months after termination, neither party shall directly or indirectly solicit or hire any employee of the other party who was involved in performing or receiving Services under this Agreement."}
    c[19] = {"id": "clause_20", "title": "Termination for Convenience", "text": "Either party may terminate this Agreement or any Statement of Work without cause at any time by providing thirty (30) days' prior written notice to the other party."}
    c[20] = {"id": "clause_21", "title": "Termination for Material Breach", "text": "Either party may terminate this Agreement immediately upon written notice if the other party commits a material breach that remains uncured for thirty (30) days after receipt of written notice describing the breach."}
    c[21] = {"id": "clause_22", "title": "Invoice Processing", "text": "Client's established accounts payable processing cycle requires a minimum of sixty (60) days from the date of invoice receipt before any payment can be issued. Vendor acknowledges and accepts this processing timeline."}
    c[22] = {"id": "clause_23", "title": "Transition Services", "text": "Upon expiration or termination, Vendor shall provide transition services for a period of ninety (90) days to ensure orderly migration of services to Client or its designated successor vendor."}
    c[23] = {"id": "clause_24", "title": "Change Management", "text": "Any changes to the scope, schedule, or fees of a Statement of Work must be documented in a written Change Order signed by authorized representatives of both parties."}
    c[24] = {"id": "clause_25", "title": "Termination for Cause", "text": "In the event of a material breach by either party, the non-breaching party may terminate this Agreement immediately upon providing fourteen (14) calendar days' written notice and an opportunity to cure."}
    c[25] = {"id": "clause_26", "title": "Governing Law", "text": "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without regard to its conflict of laws provisions."}
    c[26] = {"id": "clause_27", "title": "Dispute Resolution", "text": "Any dispute arising under this Agreement shall first be escalated to senior management of both parties for resolution. If unresolved within thirty (30) days, the dispute shall be submitted to binding arbitration under AAA Commercial Rules in Wilmington, Delaware."}
    c[27] = {"id": "clause_28", "title": "Strategic Account Exception", "text": "Notwithstanding the payment terms set forth in clause_08, strategic enterprise accounts that have been designated in writing by Vendor's Chief Financial Officer shall be eligible for extended Net 90 payment terms."}
    c[28] = {"id": "clause_29", "title": "Subcontracting", "text": "Vendor may subcontract portions of the Services to qualified third-party providers, subject to Client's prior written consent, which shall not be unreasonably withheld."}
    c[29] = {"id": "clause_30", "title": "Service Levels", "text": "Vendor shall meet the service level targets specified in each Statement of Work. Failure to meet service levels for three (3) consecutive months shall entitle Client to service credits as defined in the applicable SLA schedule."}
    c[30] = {"id": "clause_31", "title": "Indemnification Cap", "text": "The maximum aggregate liability of either party under this Agreement, including all indemnification obligations, contributions, and damages of any kind, shall not exceed One Million United States Dollars ($1,000,000)."}
    c[31] = {"id": "clause_32", "title": "Export Controls", "text": "Neither party shall export or re-export any technical data, software, or deliverables in violation of United States export control laws and regulations."}
    c[32] = {"id": "clause_33", "title": "Anti-Corruption", "text": "Each party represents and warrants that it has not and shall not offer, pay, or accept bribes or kickbacks in connection with this Agreement, in compliance with the Foreign Corrupt Practices Act and applicable local laws."}
    c[33] = {"id": "clause_34", "title": "Records Retention", "text": "Each party shall maintain complete and accurate records related to the performance of this Agreement for a period of five (5) years following termination."}
    c[34] = {"id": "clause_35", "title": "Mutual Indemnification", "text": "Each party shall be solely responsible for defending itself against any and all third-party claims arising from this Agreement. Neither party shall have any obligation to indemnify, defend, or hold harmless the other party for any claims, damages, or losses whatsoever."}
    c[35] = {"id": "clause_36", "title": "Publicity and Marketing", "text": "Neither party shall issue any press release or public statement regarding this Agreement without the prior written approval of the other party."}
    c[36] = {"id": "clause_37", "title": "Independent Contractors", "text": "The relationship between the parties is that of independent contractors. Nothing in this Agreement shall be construed to create a partnership, joint venture, agency, or employment relationship."}
    c[37] = {"id": "clause_38", "title": "Response Time SLA", "text": "Vendor shall respond to Priority 1 incidents within four (4) Business Hours, where Business Hours means any hour between 8:00 AM and 8:00 PM Eastern Time, including Saturdays but excluding Sundays and public holidays observed by the Federal Reserve."}
    c[38] = {"id": "clause_39", "title": "Background Checks", "text": "All Vendor personnel assigned to perform Services at Client facilities shall be subject to background screening consistent with Client's security policies."}
    c[39] = {"id": "clause_40", "title": "Confidentiality of Operations", "text": "Vendor's internal systems, processes, operational methodologies, and records are strictly proprietary and confidential. Client shall have no right to inspect, audit, review, or access any of Vendor's internal systems, processes, or operational records."}
    c[40] = {"id": "clause_41", "title": "Business Continuity", "text": "Vendor shall maintain a documented business continuity and disaster recovery plan and shall test such plan at least annually, providing results to Client upon request."}
    c[41] = {"id": "clause_42", "title": "Accessibility Compliance", "text": "All software deliverables shall comply with WCAG 2.1 Level AA accessibility standards and Section 508 of the Rehabilitation Act."}
    c[42] = {"id": "clause_43", "title": "Environmental Responsibility", "text": "Both parties commit to conducting their operations in an environmentally responsible manner and minimizing waste associated with the performance of Services."}
    c[43] = {"id": "clause_44", "title": "Client Insurance Obligations", "text": "Client shall be solely responsible for procuring and maintaining all insurance coverage required in connection with this Agreement, including general liability, professional liability, and cyber liability insurance. Vendor assumes no insurance obligations whatsoever under this Agreement."}
    c[44] = {"id": "clause_45", "title": "Technology Refresh", "text": "Vendor shall update all server infrastructure and software components to current supported versions at least once per calendar year, at no additional cost to Client."}
    c[45] = {"id": "clause_46", "title": "Reporting Obligations", "text": "Vendor shall provide monthly status reports detailing project progress, budget utilization, and any identified risks, delivered to Client's project manager by the fifth (5th) Business Day of each month."}
    c[46] = {"id": "clause_47", "title": "Escalation Procedures", "text": "Both parties shall follow the escalation matrix attached as Schedule C for the resolution of operational issues, service failures, and disputes."}
    c[47] = {"id": "clause_48", "title": "General Termination Notice", "text": "For termination without cause, a ninety (90) calendar day written notice period shall be strictly enforced to allow for orderly wind-down of services and transition planning."}
    c[48] = {"id": "clause_49", "title": "Acceptance Testing", "text": "Client shall have fifteen (15) Business Days from delivery to conduct acceptance testing of each Deliverable. Deliverables not rejected within this period shall be deemed accepted."}
    c[49] = {"id": "clause_50", "title": "Code of Conduct", "text": "All Vendor personnel shall adhere to Client's Code of Conduct and workplace policies while on Client premises or accessing Client systems."}
    c[50] = {"id": "clause_51", "title": "Benchmarking", "text": "Client may, once per year, engage a mutually agreed independent third party to benchmark Vendor's pricing and service levels against comparable market offerings."}
    c[51] = {"id": "clause_52", "title": "Minimum Commitment Period", "text": "Neither party may terminate this Agreement for convenience during the initial twelve (12) month term. Following the initial term, termination for convenience shall require no fewer than one hundred eighty (180) days' advance written notice."}
    c[52] = {"id": "clause_53", "title": "Survival", "text": "The following sections shall survive termination: Confidentiality, Limitation of Liability, Indemnification, Intellectual Property, and Governing Law."}
    c[53] = {"id": "clause_54", "title": "Third-Party Software", "text": "Vendor shall ensure that all third-party software incorporated into Deliverables is properly licensed and that Client receives all necessary rights to use such software."}
    c[54] = {"id": "clause_55", "title": "Severability", "text": "If any provision of this Agreement is held invalid or unenforceable, the remaining provisions shall continue in full force and effect."}
    c[55] = {"id": "clause_56", "title": "Waiver", "text": "The failure of either party to enforce any right or provision of this Agreement shall not constitute a waiver of such right or provision."}
    c[56] = {"id": "clause_57", "title": "Assignment", "text": "Neither party may assign or transfer this Agreement without the prior written consent of the other party, except in connection with a merger, acquisition, or sale of substantially all of its assets."}
    c[57] = {"id": "clause_58", "title": "Disaster Recovery", "text": "To ensure business continuity, backup replication and disaster recovery operations may be conducted in secondary facilities located outside the primary Territory, including data centers in the European Union and Asia-Pacific region."}
    c[58] = {"id": "clause_59", "title": "Entire Agreement", "text": "This Agreement, together with all Statements of Work, Change Orders, and Schedules, constitutes the entire agreement between the parties and supersedes all prior written or oral communications."}
    c[59] = {"id": "clause_60", "title": "Counterparts", "text": "This Agreement may be executed in counterparts, each of which shall be deemed an original and all of which together shall constitute one and the same instrument."}

    contradictions = [
        {"clause_a_id": "clause_05", "clause_b_id": "clause_22", "type": "numeric", "description": "Net 30 payment terms vs 60-day processing cycle."},
        {"clause_a_id": "clause_09", "clause_b_id": "clause_31", "type": "numeric", "description": "Vendor liability cap $500K vs aggregate liability cap $1M."},
        {"clause_a_id": "clause_07", "clause_b_id": "clause_18", "type": "scope", "description": "Unrestricted license to modify and create derivative works vs no modifications without written approval."},
        {"clause_a_id": "clause_13", "clause_b_id": "clause_40", "type": "scope", "description": "Client can audit Vendor's systems vs Client has no right to audit Vendor's systems."},
        {"clause_a_id": "clause_11", "clause_b_id": "clause_35", "type": "party_obligation", "description": "Vendor indemnifies Client vs neither party indemnifies the other."},
        {"clause_a_id": "clause_16", "clause_b_id": "clause_44", "type": "party_obligation", "description": "Vendor maintains insurance vs Client solely responsible for all insurance."},
        {"clause_a_id": "clause_20", "clause_b_id": "clause_52", "type": "temporal", "description": "30-day termination anytime vs no convenience termination during first 12 months and 180-day notice after."},
        {"clause_a_id": "clause_02", "clause_b_id": "clause_38", "type": "definition", "description": "Business Day excludes Saturday vs Business Hours includes Saturday."},
    ]
    traps = [
        {"clause_a_id": "clause_25", "clause_b_id": "clause_48", "reason": "Different contexts: 14 days for termination for cause vs 90 days for termination without cause."},
        {"clause_a_id": "clause_08", "clause_b_id": "clause_28", "reason": "Explicit override: clause_28 uses 'Notwithstanding clause_08' to create an intentional exception for strategic accounts."},
        {"clause_a_id": "clause_14", "clause_b_id": "clause_58", "reason": "Complementary scope: primary processing in Territory vs disaster recovery outside Territory — different activities."},
    ]
    create_contract("hard_001.json", "hard_001", "hard", "Master Service Agreement between Apex Systems Corp and MegaRetail Group", c, contradictions, traps)

def build_hard_002():
    c = []
    for i in range(1, 61):
        c.append({"id": f"clause_{i:02d}", "title": f"Financial Technology Provision {i}", "text": f"Standard provision governing the technology licensing relationship between Licensor and Licensee in connection with financial services software and related regulatory compliance obligations under applicable banking regulations. Section {i} applies."})

    c[0] = {"id": "clause_01", "title": "Preamble and Recitals", "text": "This Technology Licensing and Services Agreement (\"Agreement\") is entered into between CoreTech Innovations, a Delaware corporation (\"Licensor\"), and GlobalBank Financial, a national banking association chartered under the laws of the United States (\"Licensee\"). Licensor has developed proprietary financial technology software and Licensee desires to license such software."}
    c[1] = {"id": "clause_02", "title": "Definitions", "text": "\"Platform\" means the proprietary financial technology software suite. \"Licensed Territory\" means the United States, Canada, and the United Kingdom. \"Regulatory Authority\" means any federal, state, or foreign financial regulator with jurisdiction. \"Service Credits\" means monetary credits issued for SLA failures."}
    c[2] = {"id": "clause_03", "title": "Data Retention", "text": "Licensor agrees to retain all system logs, transaction metadata, audit trails, and processing records for a strictly limited period of twelve (12) months from the date of creation, after which such records shall be permanently and irretrievably deleted."}
    c[3] = {"id": "clause_04", "title": "License Grant", "text": "Licensor grants Licensee a non-exclusive, non-transferable license to use the Platform within the Licensed Territory for the processing of financial transactions, regulatory reporting, and internal risk management analytics."}
    c[4] = {"id": "clause_05", "title": "Definition of Confidential Information", "text": "\"Confidential Information\" means all non-public information disclosed by either party, including source code, algorithms, and customer data. Confidential Information shall strictly exclude any transactional data that has been fully anonymized and aggregated, which may be freely used for statistical and benchmarking purposes."}
    c[5] = {"id": "clause_06", "title": "Fees and Payment", "text": "Licensee shall pay an annual license fee as set forth in the applicable Order Form, plus per-transaction fees for processing volumes exceeding the base tier. All fees are non-refundable."}
    c[6] = {"id": "clause_07", "title": "Implementation Services", "text": "Licensor shall provide implementation services including installation, configuration, data migration, integration with Licensee's core banking systems, and user acceptance testing support over a period not to exceed one hundred twenty (120) days."}
    c[7] = {"id": "clause_08", "title": "Availability SLA", "text": "The Platform shall maintain an availability rate of no less than 99.9% uptime measured on a calendar month basis, excluding scheduled maintenance windows communicated at least seventy-two (72) hours in advance."}
    c[8] = {"id": "clause_09", "title": "Support Tiers", "text": "Licensor shall provide three tiers of technical support: Tier 1 (self-service knowledge base), Tier 2 (email and phone support during business hours), and Tier 3 (dedicated engineering escalation for critical issues)."}
    c[9] = {"id": "clause_10", "title": "Source Code Escrow", "text": "Licensor agrees to deposit the complete Platform source code, including all libraries, build scripts, and documentation, into escrow with a mutually agreed escrow agent within thirty (30) days of the Effective Date, for the benefit and protection of Licensee."}
    c[10] = {"id": "clause_11", "title": "Acceptance Testing", "text": "Licensee shall have thirty (30) Business Days from delivery to conduct acceptance testing. Deliverables not formally rejected within this period shall be deemed accepted."}
    c[11] = {"id": "clause_12", "title": "Compliance Records", "text": "To satisfy New York Department of Financial Services (DFS) regulatory requirements and federal banking record retention mandates, all system logs, transaction metadata, audit trails, and processing records shall be continuously preserved by Licensor for a minimum of five (5) years from the date of creation."}
    c[12] = {"id": "clause_13", "title": "Base Support Scope", "text": "The base support package exclusively covers Severity Level 3 and Severity Level 4 tickets and is available only during regional business hours as defined in the applicable country addendum."}
    c[13] = {"id": "clause_14", "title": "Change Management", "text": "All changes to the Platform's production environment shall follow Licensor's ITIL-aligned change management process, including impact assessment, approval by the Change Advisory Board, and post-implementation review."}
    c[14] = {"id": "clause_15", "title": "Hosting Options", "text": "Licensee may at its sole discretion deploy the licensed Platform across multiple public cloud architectures, including Amazon Web Services, Microsoft Azure, and Google Cloud Platform, in any availability zone within the Licensed Territory."}
    c[15] = {"id": "clause_16", "title": "General Release", "text": "Major feature releases and version upgrades shall be automatically pushed to all designated sandbox and development environments for regression testing prior to production deployment."}
    c[16] = {"id": "clause_17", "title": "Warranties", "text": "Licensor warrants that the Platform shall perform materially in accordance with its published specifications and that Licensor has the legal right and authority to grant the licenses contemplated herein."}
    c[17] = {"id": "clause_18", "title": "Penetration Testing", "text": "Licensee is authorized and expected to conduct quarterly penetration tests on the Platform using Licensee's authorized third-party security vendors at Licensee's own expense, to verify the security posture of the hosted environment."}
    c[18] = {"id": "clause_19", "title": "Indemnification by Licensor", "text": "Licensor shall indemnify, defend, and hold harmless Licensee from and against all claims arising from infringement of any third-party intellectual property rights by the Platform."}
    c[19] = {"id": "clause_20", "title": "PCI Compliance", "text": "Licensor shall obtain, maintain, and demonstrate SOC 2 Type II and PCI-DSS Level 1 compliance across all hosted infrastructure and shall be solely responsible for the costs of initial certification and annual recertification."}
    c[20] = {"id": "clause_21", "title": "Data Classification", "text": "Licensee's data shall be classified into four tiers: Public, Internal, Confidential, and Restricted. Each tier is subject to specific handling, encryption, and access control requirements."}
    c[21] = {"id": "clause_22", "title": "Liability for Fraud by Authorized Users", "text": "Licensor shall have no liability for any fraudulent transactions executed by Licensee's authorized users acting within the scope of their system permissions and access credentials."}
    c[22] = {"id": "clause_23", "title": "Limitation of Liability", "text": "In no event shall either party's total aggregate liability under this Agreement exceed the total license and service fees paid or payable during the twelve (12) months immediately preceding the event giving rise to the claim."}
    c[23] = {"id": "clause_24", "title": "Termination for Convenience", "text": "Either party may terminate this Agreement upon ninety (90) days' prior written notice to the other party, provided that all outstanding fees are paid through the termination date."}
    c[24] = {"id": "clause_25", "title": "Deployment Limitations", "text": "Deployment of the licensed Platform is strictly prohibited in multi-tenant public cloud environments. The Platform shall be deployed solely on Licensee's private, dedicated bare-metal infrastructure within Licensee's own data centers."}
    c[25] = {"id": "clause_26", "title": "Regulatory Cooperation", "text": "Licensor shall cooperate fully with Licensee and any applicable Regulatory Authority in connection with examinations, investigations, or audits relating to the Platform or the Services."}
    c[26] = {"id": "clause_27", "title": "Transition Services", "text": "Upon termination, Licensor shall provide transition assistance for a period of one hundred eighty (180) days, including data export, knowledge transfer, and parallel operation support."}
    c[27] = {"id": "clause_28", "title": "Force Majeure", "text": "Neither party shall be liable for failures in performance resulting from events beyond its reasonable control, including natural disasters, acts of terrorism, epidemics, cyberattacks, or government-imposed sanctions."}
    c[28] = {"id": "clause_29", "title": "Export Controls", "text": "Neither party shall export or re-export any software, technical data, or deliverables in violation of U.S. Export Administration Regulations or OFAC sanctions."}
    c[29] = {"id": "clause_30", "title": "Security Audits", "text": "Under no circumstances shall the Licensee or any party acting on Licensee's behalf subject the Platform to penetration testing, vulnerability scanning, or any form of security assessment. All such testing shall be conducted exclusively by Licensor's internal information security team."}
    c[30] = {"id": "clause_31", "title": "Anti-Money Laundering", "text": "Both parties shall comply with all applicable anti-money laundering laws and regulations, including the Bank Secrecy Act and USA PATRIOT Act."}
    c[31] = {"id": "clause_32", "title": "Disaster Recovery", "text": "Licensor shall maintain a comprehensive disaster recovery plan with a Recovery Time Objective (RTO) of four (4) hours and Recovery Point Objective (RPO) of one (1) hour for all critical systems."}
    c[32] = {"id": "clause_33", "title": "Encryption Standards", "text": "All data at rest shall be encrypted using AES-256 or equivalent. All data in transit shall be encrypted using TLS 1.3 or higher. Encryption key management shall follow NIST SP 800-57 guidelines."}
    c[33] = {"id": "clause_34", "title": "Service Credit Mechanics", "text": "For each 0.1% of downtime below the guaranteed SLA threshold, Licensor shall issue a service credit equal to 5% of the monthly fees, up to a maximum of 30% of such monthly fees."}
    c[34] = {"id": "clause_35", "title": "Force Majeure Notice", "text": "A party affected by a Force Majeure event must provide formal written notice to the other party within forty-eight (48) hours of the commencement of such event, specifying the nature, expected duration, and steps being taken to mitigate its impact."}
    c[35] = {"id": "clause_36", "title": "Governing Law", "text": "This Agreement shall be governed by and construed in accordance with the laws of the State of New York, without regard to its conflict of laws provisions."}
    c[36] = {"id": "clause_37", "title": "Dispute Resolution", "text": "Any dispute shall be resolved through binding arbitration under the rules of the American Arbitration Association, with proceedings held in New York City. The arbitration panel shall consist of three arbitrators experienced in financial technology."}
    c[37] = {"id": "clause_38", "title": "Uptime Requirements", "text": "Licensor is bound to maintain an availability rate of no less than 99.999% uptime for all Tier 1 critical banking applications, measured against a rolling seven-day window. Any deviation shall constitute a material breach."}
    c[38] = {"id": "clause_39", "title": "Background Checks", "text": "All Licensor personnel with access to Licensee systems or data shall undergo comprehensive background checks, including criminal history, credit history, and OFAC screening."}
    c[39] = {"id": "clause_40", "title": "Proprietary Core", "text": "The core algorithmic trading engine, risk modeling framework, and associated machine learning models are highly proprietary and classified as Licensor Trade Secrets. These components are expressly exempt from any source code escrow, inspection, or disclosure obligations under this Agreement or any applicable law."}
    c[40] = {"id": "clause_41", "title": "Incident Response", "text": "In the event of a data breach or security incident, Licensor shall notify Licensee within twenty-four (24) hours and cooperate fully in the investigation and remediation."}
    c[41] = {"id": "clause_42", "title": "Multi-Factor Authentication", "text": "Access to the Platform shall require multi-factor authentication for all users, including API service accounts processing financial transactions."}
    c[42] = {"id": "clause_43", "title": "Premium Add-On", "text": "Subject to payment of the Premium Support Fee set forth in Schedule B, Severity Level 1 and Severity Level 2 tickets shall be serviced on a 24/7/365 basis with guaranteed initial response times of fifteen (15) minutes for Severity 1 and one (1) hour for Severity 2."}
    c[43] = {"id": "clause_44", "title": "Access Control", "text": "Licensor shall implement role-based access controls aligned with the principle of least privilege. Access reviews shall be conducted quarterly."}
    c[44] = {"id": "clause_45", "title": "Emergency Declarations", "text": "In the event of a banking holiday, systemic market outage, or industry-wide disruption qualifying as Force Majeure, formal written notice of the Force Majeure event may be delayed for up to fourteen (14) calendar days without penalty or adverse consequence to the affected party."}
    c[45] = {"id": "clause_46", "title": "Production Freeze", "text": "Notwithstanding clause_16, no automated code pushes, version updates, or feature releases shall be deployed to any production environment without explicit manual approval from Licensee's Technology Change Advisory Board."}
    c[46] = {"id": "clause_47", "title": "Audit Rights", "text": "Licensee and any applicable Regulatory Authority shall have the right to audit Licensor's facilities, systems, processes, and records upon thirty (30) days' written notice."}
    c[47] = {"id": "clause_48", "title": "Non-Solicitation", "text": "During the term and for eighteen (18) months following termination, neither party shall solicit or hire any key employee of the other party."}
    c[48] = {"id": "clause_49", "title": "Assignment", "text": "Neither party may assign this Agreement without the other party's consent, except in connection with a merger, acquisition, or sale of substantially all assets."}
    c[49] = {"id": "clause_50", "title": "Data Aggregation Rights", "text": "Even after undergoing full anonymization and aggregation, all transactional data processed through the Platform retains its classification as Confidential Information and may not be shared, distributed, sold, or made available to any third party, including for statistical or benchmarking purposes."}
    c[50] = {"id": "clause_51", "title": "Survival", "text": "The following provisions shall survive termination: Confidentiality, Limitation of Liability, Indemnification, Intellectual Property, Data Retention, and Governing Law."}
    c[51] = {"id": "clause_52", "title": "Liability for Intrusion", "text": "Licensor assumes full and complete liability for all fraudulent transactions that are caused directly by an unauthorized breach of Licensor's network security perimeter by an external malicious actor exploiting a vulnerability in Licensor's infrastructure."}
    c[52] = {"id": "clause_53", "title": "Notices", "text": "All notices shall be in writing and delivered by certified mail, overnight courier, or secure email to the addresses specified in the signature block."}
    c[53] = {"id": "clause_54", "title": "Severability", "text": "If any provision is held invalid or unenforceable, the remaining provisions shall continue in full force and effect."}
    c[54] = {"id": "clause_55", "title": "Regulatory Certifications", "text": "Licensee shall absorb the full cost and sole responsibility for attaining and maintaining all PCI-DSS certifications, SOC 2 attestations, and related regulatory compliance certifications for the hosted environment and all associated infrastructure."}
    c[55] = {"id": "clause_56", "title": "Waiver", "text": "Failure to enforce any provision shall not constitute a waiver of that provision or the right to enforce it at a later time."}
    c[56] = {"id": "clause_57", "title": "Amendments", "text": "This Agreement may be amended only by a written instrument signed by authorized representatives of both parties."}
    c[57] = {"id": "clause_58", "title": "Third-Party Beneficiaries", "text": "This Agreement is for the sole benefit of the parties hereto and does not create any rights in favor of any third party."}
    c[58] = {"id": "clause_59", "title": "Entire Agreement", "text": "This Agreement, together with all Order Forms and Schedules, constitutes the entire agreement and supersedes all prior negotiations and agreements."}
    c[59] = {"id": "clause_60", "title": "Counterparts", "text": "This Agreement may be executed in counterparts, each deemed an original and all together constituting one instrument."}

    contradictions = [
        {"clause_a_id": "clause_03", "clause_b_id": "clause_12", "type": "numeric", "description": "12-month retention vs 5-year retention for the same system logs and transaction metadata."},
        {"clause_a_id": "clause_15", "clause_b_id": "clause_25", "type": "scope", "description": "Public cloud deployment permitted vs prohibited — restricted to private bare-metal only."},
        {"clause_a_id": "clause_18", "clause_b_id": "clause_30", "type": "party_obligation", "description": "Licensee authorized to conduct pen testing vs Licensee prohibited from pen testing."},
        {"clause_a_id": "clause_35", "clause_b_id": "clause_45", "type": "temporal", "description": "48-hour Force Majeure notice vs 14-day delay allowed."},
        {"clause_a_id": "clause_05", "clause_b_id": "clause_50", "type": "definition", "description": "Anonymized data excluded from Confidential Information vs anonymized data remains Confidential."},
        {"clause_a_id": "clause_08", "clause_b_id": "clause_38", "type": "numeric", "description": "99.9% uptime SLA vs 99.999% uptime requirement."},
        {"clause_a_id": "clause_10", "clause_b_id": "clause_40", "type": "scope", "description": "Complete source code escrow vs core algorithmic engine exempt from escrow."},
        {"clause_a_id": "clause_20", "clause_b_id": "clause_55", "type": "party_obligation", "description": "Licensor responsible for PCI-DSS certifications vs Licensee bears full cost and responsibility."},
    ]
    traps = [
        {"clause_a_id": "clause_13", "clause_b_id": "clause_43", "reason": "Different service tiers: Base support covers Sev 3-4 during business hours, Premium add-on covers Sev 1-2 24/7."},
        {"clause_a_id": "clause_16", "clause_b_id": "clause_46", "reason": "Explicit override: clause_46 says 'Notwithstanding clause_16' for production environments specifically."},
        {"clause_a_id": "clause_22", "clause_b_id": "clause_52", "reason": "Different scenarios: authorized user fraud vs external intrusion — different actors and different liability triggers."},
    ]
    create_contract("hard_002.json", "hard_002", "hard", "Technology Licensing and Services Agreement between CoreTech Innovations and GlobalBank Financial", c, contradictions, traps)

if __name__ == "__main__":
    build_easy_001()
    build_easy_002()
    build_medium_001()
    build_medium_002()
    build_hard_001()
    build_hard_002()
    print("All 6 contracts generated successfully.")
