import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { resetEpisode, submitFindings } from '../utils/api'
import { runAgent } from '../utils/agent'
import { useApiConfig } from '../hooks/useApiConfig'

export default function ComparePage() {
  const nav = useNavigate()
  const [leftObs, setLeftObs] = useState(null)
  const [rightObs, setRightObs] = useState(null)
  const [leftFindings, setLeftFindings] = useState([])
  const [rightFindings, setRightFindings] = useState([])
  const [leftResult, setLeftResult] = useState(null)
  const [rightResult, setRightResult] = useState(null)
  const [leftTask, setLeftTask] = useState('easy')
  const [rightTask, setRightTask] = useState('medium')
  const [loading, setLoading] = useState({ left: false, right: false })
  
  const [apiConfig] = useApiConfig();
  const hasKey = apiConfig?.keys?.[apiConfig?.provider]

  const loadDemoData = () => {
    setLoading({ left: true, right: true })
    setTimeout(() => {
      setLeftTask('medium')
      setRightTask('hard')
      
      setLeftObs({
        task_id: 'medium',
        clauses: [
          { id: 'SaaS-01', text: '"Service" means the cloud-hosted platform, APIs, dashboards, and all related documentation provided by Provider under this Agreement.' },
          { id: 'SaaS-05', text: 'Provider grants Client a non-exclusive, worldwide, perpetual license to use the Service for any lawful business purpose including derivative works and sub-licensing.' },
          { id: 'SaaS-08', text: 'Client shall not sub-license, resell, distribute, or create derivative works based on the Service without prior written approval from Provider.' },
          { id: 'SaaS-12', text: 'Provider guarantees 99.9% monthly uptime. Scheduled maintenance windows (max 4 hours/month) are excluded from uptime calculations.' },
          { id: 'SaaS-15', text: 'If monthly uptime falls below 99.9%, Client is entitled to a service credit equal to 10% of the monthly fee for each 0.1% below the threshold, up to 30%.' },
          { id: 'SaaS-22', text: 'All data uploaded or generated by Client remains the exclusive intellectual property of the Client. Provider shall not access, use, or monetize Client data.' },
          { id: 'SaaS-27', text: 'Provider may collect, aggregate, and analyze usage data and Client-generated content to improve the Service, train ML models, and create anonymized benchmarks.' },
          { id: 'SaaS-44', text: 'Under no circumstances shall Provider issue credits, refunds, or financial compensation of any kind exceeding the fees paid in the prior 3 months.' }
        ]
      })
      setRightObs({
        task_id: 'hard',
        clauses: [
          { id: 'MSA-01', text: '"Confidential Information" includes all business, technical, financial, and operational information disclosed by either party.' },
          { id: 'MSA-04', text: 'Governing Law: This agreement shall be governed by and construed in accordance with the laws of the State of Delaware.' },
          { id: 'MSA-09', text: 'Force Majeure: Neither party shall be liable for failures caused by events beyond reasonable control, including natural disasters, pandemics, or government actions.' },
          { id: 'MSA-14', text: 'Warranty: Provider warrants that the deliverables will be free from material defects and will conform to the specifications for a period of 12 months.' },
          { id: 'MSA-19', text: 'Dispute Resolution: All disputes arising under this Agreement must be settled through binding arbitration in New York City under AAA rules.' },
          { id: 'MSA-25', text: 'Indemnification: Provider shall indemnify Client against all claims arising from Provider\'s negligence, including legal fees without any cap on liability.' },
          { id: 'MSA-30', text: 'Liability Cap: In no event shall either party\'s total aggregate liability exceed the amounts paid under this Agreement in the 12 months preceding the claim.' },
          { id: 'MSA-33', text: 'Jurisdiction: The parties agree to the exclusive jurisdiction of the state and federal courts located in San Francisco, California.' }
        ]
      })
      
      setLeftFindings([
        { clause_a_id: 'SaaS-05', clause_b_id: 'SaaS-08', explanation: 'License Grant permits derivative works and sub-licensing, but Usage Restrictions explicitly forbids both activities without prior written approval. Direct scope contradiction.', confidence: 0.96 },
        { clause_a_id: 'SaaS-15', clause_b_id: 'SaaS-44', explanation: 'SLA Credit clause promises up to 30% monthly credit for downtime. Limitation of Liability blanket-prohibits all credits, refunds, and compensation. Irreconcilable conflict.', confidence: 0.98 },
        { clause_a_id: 'SaaS-22', clause_b_id: 'SaaS-27', explanation: 'Data Ownership clause bars Provider from accessing or monetizing Client data. Analytics clause grants Provider rights to collect and analyze Client-generated content for ML training.', confidence: 0.91 }
      ])
      setRightFindings([
        { clause_a_id: 'MSA-19', clause_b_id: 'MSA-33', explanation: 'Mandatory binding arbitration in New York (MSA-19) directly conflicts with exclusive court jurisdiction in San Francisco (MSA-33). Cannot simultaneously require arbitration and litigation.', confidence: 0.95 },
        { clause_a_id: 'MSA-04', clause_b_id: 'MSA-33', explanation: 'Delaware governing law (MSA-04) may conflict with California jurisdiction (MSA-33) — courts in California may apply California procedural rules rather than Delaware substantive law.', confidence: 0.72 },
        { clause_a_id: 'MSA-25', clause_b_id: 'MSA-30', explanation: 'Indemnification clause (MSA-25) promises uncapped liability coverage including legal fees. Liability Cap (MSA-30) limits total aggregate liability to 12 months of fees. Direct monetary conflict.', confidence: 0.94 },
        { clause_a_id: 'MSA-09', clause_b_id: 'MSA-14', explanation: 'Force Majeure (MSA-09) excuses performance failures from external events. Warranty clause (MSA-14) guarantees deliverables will be defect-free for 12 months with no force majeure carve-out.', confidence: 0.68 }
      ])
      
      setLeftResult({ score: 0.92, feedback: 'Correctly identified: 3/3 contradictions. False positives: 0. Excellent multi-domain analysis across SLA, licensing, and data rights.' })
      setRightResult({ score: 0.78, feedback: 'Correctly identified: 3/4 contradictions. Missed Force Majeure vs Warranty conflict. Strong jurisdictional analysis.' })
      setLoading({ left: false, right: false })
    }, 600)
  }

  // Run both simultaneously
  const runBoth = async () => {
    setLoading({ left: true, right: true })
    setLeftFindings([])
    setRightFindings([])
    setLeftResult(null)
    setRightResult(null)

    try {
      const [lObs, rObs] = await Promise.all([
        resetEpisode(leftTask),
        resetEpisode(rightTask)
      ])
      setLeftObs(lObs)
      setRightObs(rObs)

      const [lData, rData] = await Promise.all([
        runAgent(lObs, apiConfig),
        runAgent(rObs, apiConfig)
      ])
      setLeftFindings(lData || [])
      setRightFindings(rData || [])

      const [lRes, rRes] = await Promise.all([
        submitFindings(lData || [], leftTask),
        submitFindings(rData || [], rightTask)
      ])
      setLeftResult(lRes)
      setRightResult(rRes)
    } catch (e) {
      console.error(e)
    }
    setLoading({ left: false, right: false })
  }

  const scoreColor = s => s >= 0.7 ? 'var(--green)' : s >= 0.4 ? 'var(--amber)' : 'var(--red)'

  return (
    <div style={{ minHeight: '100vh', background: '#E8EAFB' }}>
      {/* Header */}
      <div style={{
        height: '52px', background: '#FFFFFF',
        borderBottom: '1px solid rgba(108,99,255,0.1)',
        display: 'flex', alignItems: 'center',
        justifyContent: 'space-between', padding: '0 20px',
        boxShadow: '0 2px 12px rgba(108,99,255,0.05)'
      }}>
        <button onClick={() => nav('/app')} style={{
          background: '#F5F4FF', border: 'none', color: '#1a1a2e',
          fontSize: '13px', cursor: 'pointer', fontWeight: '600',
          borderRadius: '12px', padding: '6px 14px'
        }}>← Back</button>
        <span style={{ fontWeight: '700', fontSize: '15px', color: '#1a1a2e' }}>⇄ Contract Comparison — Clausr</span>
        <div style={{ display: 'flex', gap: '10px' }}>
          <button onClick={loadDemoData} style={{
            padding: '7px 16px', background: '#FFF0EB', border: '1px solid rgba(255,100,50,0.3)',
            borderRadius: '12px', color: '#e85d30', fontSize: '13px',
            fontWeight: '600', cursor: 'pointer', transition: '0.2s'
          }}>
            🔥 Load Demo
          </button>
          <button onClick={runBoth} disabled={!hasKey} style={{
            padding: '7px 20px', background: '#6C63FF', border: 'none',
            borderRadius: '12px', color: '#fff', fontSize: '13px',
            fontWeight: '600', cursor: hasKey ? 'pointer' : 'not-allowed',
            opacity: hasKey ? 1 : 0.5, transition: 'all 150ms ease'
          }}>
            {loading.left || loading.right ? 'Running...' : 'Run Both Agents →'}
          </button>
        </div>
      </div>

      {/* Task selectors */}
      <div style={{
        display: 'grid', gridTemplateColumns: '1fr 1fr',
        gap: '1px', background: 'rgba(108,99,255,0.08)', borderBottom: '1px solid rgba(108,99,255,0.1)'
      }}>
        {[
          { task: leftTask, setTask: setLeftTask, side: 'Left', result: leftResult },
          { task: rightTask, setTask: setRightTask, side: 'Right', result: rightResult }
        ].map(({ task, setTask, side, result }) => (
          <div key={side} style={{
            background: '#FFFFFF', padding: '12px 20px',
            display: 'flex', alignItems: 'center', gap: '12px'
          }}>
            <span style={{ fontSize: '12px', color: '#1a1a2e', fontWeight: '700' }}>{side}:</span>
            <select value={task} onChange={e => setTask(e.target.value)} style={{
              padding: '6px 10px', background: '#F5F4FF',
              border: '1px solid rgba(108,99,255,0.15)', borderRadius: '8px',
              color: '#1a1a2e', fontSize: '12px', outline: 'none', fontWeight: '500'
            }}>
              <option value="easy">Easy — NDA</option>
              <option value="medium">Medium — SaaS</option>
              <option value="hard">Hard — MSA</option>
            </select>
            {result && result.score !== undefined && (
              <div style={{
                marginLeft: 'auto', fontSize: '22px', fontWeight: '800',
                color: scoreColor(result.score)
              }}>
                {result.score?.toFixed(2)}
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Side by side content */}
      <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '1px', background: 'rgba(108,99,255,0.08)', minHeight: 'calc(100vh - 108px)' }}>
        {[
          { obs: leftObs, findings: leftFindings, result: leftResult, loading: loading.left },
          { obs: rightObs, findings: rightFindings, result: rightResult, loading: loading.right }
        ].map((side, idx) => (
          <div key={idx} style={{ background: '#F0F1FC', overflowY: 'auto', maxHeight: 'calc(100vh - 108px)' }}>
            {!side.obs && !side.loading && (
              <div style={{ textAlign: 'center', padding: '60px 20px', color: '#2a2a48', fontWeight: '600' }}>
                Click "Run Both Agents" to start
              </div>
            )}
            {side.loading && (
              <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '200px', gap: '12px' }}>
                <div className="spin" style={{ width: '24px', height: '24px' }} />
                <p style={{ color: '#4a4a6a', fontSize: '13px', fontWeight: '500' }}>Agent analyzing...</p>
              </div>
            )}
            {side.obs && !side.loading && (
              <div style={{ padding: '16px' }}>
                {/* Score banner */}
                {side.result && side.result.score !== undefined && (
                  <div style={{
                    background: '#FFFFFF',
                    border: `2px solid ${scoreColor(side.result.score)}`,
                    borderRadius: '14px', padding: '14px 18px', marginBottom: '16px',
                    display: 'flex', alignItems: 'center', gap: '14px',
                    boxShadow: '0 2px 12px rgba(108,99,255,0.06)'
                  }}>
                    <span style={{ fontSize: '30px', fontWeight: '800', color: scoreColor(side.result.score) }}>
                      {side.result.score?.toFixed(2)}
                    </span>
                    <span style={{ fontSize: '13px', color: '#1a1a2e', flex: 1, lineHeight: '1.5', fontWeight: '500' }}>
                      {side.result.feedback}
                    </span>
                  </div>
                )}
                {/* Findings */}
                {side.findings.map((f, i) => (
                  <div key={i} style={{
                    border: '1px solid rgba(108,99,255,0.1)', borderRadius: '14px',
                    padding: '14px 16px', marginBottom: '10px', background: '#FFFFFF',
                    boxShadow: '0 2px 8px rgba(108,99,255,0.04)', transition: 'transform 0.2s',
                  }}>
                    <div style={{ display: 'flex', gap: '8px', marginBottom: '8px', alignItems: 'center' }}>
                      <span style={{ fontFamily: 'monospace', fontSize: '11px', color: '#6C63FF', background: '#F0EEFF', padding: '3px 8px', borderRadius: '6px', fontWeight: '600' }}>{f.clause_a_id}</span>
                      <span style={{ fontSize: '11px', color: '#4a4a6a', fontWeight: '700' }}>vs</span>
                      <span style={{ fontFamily: 'monospace', fontSize: '11px', color: '#6C63FF', background: '#F0EEFF', padding: '3px 8px', borderRadius: '6px', fontWeight: '600' }}>{f.clause_b_id}</span>
                    </div>
                    <p style={{ fontSize: '13px', color: '#2d2d44', margin: 0, lineHeight: '1.7', fontWeight: '400' }}>{f.explanation}</p>
                    {f.confidence !== undefined && (
                      <div style={{ height: '3px', background: '#EEEDFE', borderRadius: '2px', marginTop: '10px', overflow: 'hidden' }}>
                        <div style={{ height: '100%', width: `${f.confidence * 100}%`, background: '#6C63FF', borderRadius: '2px' }} />
                      </div>
                    )}
                  </div>
                ))}
                {/* Clause count */}
                <p style={{ fontSize: '11px', color: '#2a2a48', textAlign: 'center', marginTop: '14px', fontWeight: '600' }}>
                  {side.obs.clauses?.length} clauses · {side.obs.task_id} task
                </p>
              </div>
            )}
          </div>
        ))}
      </div>

      {/* Score comparison bar */}
      {leftResult && rightResult && leftResult.score !== null && rightResult.score !== null && (
        <div style={{
          position: 'fixed', bottom: 0, left: 0, right: 0,
          background: '#FFFFFF', borderTop: '1px solid rgba(108,99,255,0.1)',
          padding: '12px 20px', display: 'flex', alignItems: 'center', gap: '16px',
          boxShadow: '0 -2px 16px rgba(108,99,255,0.06)'
        }}>
          <span style={{ fontSize: '13px', fontWeight: '700', color: scoreColor(leftResult.score) }}>
            {leftTask.toUpperCase()}: {leftResult.score?.toFixed(2)}
          </span>
          <div style={{ flex: 1, height: '6px', background: '#EEEDFE', borderRadius: '3px', overflow: 'hidden', display: 'flex' }}>
            <div style={{ height: '100%', width: `${leftResult.score * 50}%`, background: scoreColor(leftResult.score), borderRadius: '3px' }} />
            <div style={{ height: '100%', width: `${rightResult.score * 50}%`, background: scoreColor(rightResult.score), marginLeft: 'auto', borderRadius: '3px' }} />
          </div>
          <span style={{ fontSize: '13px', fontWeight: '700', color: scoreColor(rightResult.score) }}>
            {rightTask.toUpperCase()}: {rightResult.score?.toFixed(2)}
          </span>
          <span style={{ fontSize: '12px', color: '#4a4a68', marginLeft: '8px', fontWeight: '500' }}>
            {leftResult.score > rightResult.score
              ? `← ${leftTask} scores ${((leftResult.score - rightResult.score) * 100).toFixed(0)}pts higher`
              : rightResult.score > leftResult.score
              ? `${rightTask} scores ${((rightResult.score - leftResult.score) * 100).toFixed(0)}pts higher →`
              : 'Tied'}
          </span>
        </div>
      )}
    </div>
  )
}
