/**
 * Demo Portfolio Data Generator
 * Provides realistic contract data for demonstrating Portfolio Analysis features
 */

export const DEMO_CONTRACTS = [
  {
    id: 'CONTRACT_1',
    name: 'NDA — Acme Corp',
    contract_text: 'Non-Disclosure Agreement between TechFlow Inc. and Acme Corp.',
    instructions: 'Identify contradictions between these contracts in a portfolio.',
    clauses: [
      { id: 'clause_01', title: 'Definition of Confidential Information', text: '"Confidential Information" means any and all non-public technical, business, financial, or operational information disclosed by either party, including trade secrets, algorithms, customer lists, pricing strategies, and product roadmaps, whether disclosed orally, in writing, or electronically.' },
      { id: 'clause_02', title: 'Obligations of Receiving Party', text: 'The Receiving Party shall hold all Confidential Information in strict confidence and shall not disclose it to any third party without prior written consent. The Receiving Party shall use the same degree of care as it uses to protect its own confidential information, but no less than reasonable care.' },
      { id: 'clause_03', title: 'Term of Confidentiality', text: 'This Agreement shall remain in effect for a period of three (3) years from the Effective Date. The obligations of confidentiality shall survive termination and continue for five (5) years after disclosure of the Confidential Information.' },
      { id: 'clause_04', title: 'Permitted Disclosures', text: 'Notwithstanding the foregoing, the Receiving Party may disclose Confidential Information to its employees, contractors, and advisors who have a need to know and who are bound by confidentiality obligations no less restrictive than those contained herein.' },
      { id: 'clause_05', title: 'Return of Materials', text: 'Upon termination, the Receiving Party shall promptly return or destroy all Confidential Information, including copies and derivatives, within thirty (30) calendar days and provide written certification of destruction.' },
      { id: 'clause_06', title: 'Remedies', text: 'The parties acknowledge that a breach of this Agreement would cause irreparable harm. In addition to any other remedies available at law or in equity, the Disclosing Party shall be entitled to seek injunctive relief without posting bond.' },
    ]
  },
  {
    id: 'CONTRACT_2',
    name: 'SaaS License — CloudVault',
    contract_text: 'SaaS Platform License Agreement between CloudVault Technologies and Meridian Financial Group.',
    instructions: 'Identify contradictions between these contracts in a portfolio.',
    clauses: [
      { id: 'clause_01', title: 'Service Definition', text: '"Service" means the CloudVault enterprise data management platform, including all associated APIs, dashboards, storage infrastructure, and documentation. "Subscription Term" means the period during which Client has authorized access to the Service.' },
      { id: 'clause_02', title: 'License Grant', text: 'Provider grants Client a non-exclusive, non-transferable license to access and use the Service during the Subscription Term solely for Client\'s internal business operations. Client shall not sublicense, resell, or distribute access to the Service to any third party.' },
      { id: 'clause_03', title: 'Data Ownership', text: 'All data uploaded, stored, processed, or generated by Client through the Service ("Client Data") shall remain the exclusive property of Client. Provider acquires no rights, title, or interest in Client Data and shall not access, use, analyze, or monetize Client Data for any purpose other than providing the Service.' },
      { id: 'clause_04', title: 'Uptime SLA', text: 'Provider guarantees 99.95% monthly uptime availability for the Service. Scheduled maintenance windows of up to four (4) hours per month shall be excluded from uptime calculations. Provider shall notify Client 48 hours in advance of scheduled maintenance.' },
      { id: 'clause_05', title: 'Data Analytics License', text: 'Client grants Provider a non-exclusive, royalty-free license to collect, aggregate, analyze, and create derivative works from Client Data for improving the Service, developing new features, training machine learning models, and generating anonymized industry benchmarks.' },
      { id: 'clause_06', title: 'Termination for Convenience', text: 'Either party may terminate this Agreement at any time without cause by providing thirty (30) calendar days written notice. Upon such termination, Client shall pay all fees accrued through the effective date of termination.' },
      { id: 'clause_07', title: 'Auto-Renewal', text: 'This Agreement shall automatically renew for successive twelve (12) month periods unless either party provides written notice of non-renewal at least ninety (90) days prior to the end of the then-current term.' },
      { id: 'clause_08', title: 'Limitation of Liability', text: 'In no event shall either party\'s total aggregate liability under this Agreement exceed the total fees paid by Client during the twelve (12) month period immediately preceding the event. Neither party shall be liable for any indirect, incidental, consequential, or punitive damages.' },
    ]
  },
  {
    id: 'CONTRACT_3',
    name: 'Consulting — Vertex Advisory',
    contract_text: 'Professional Consulting Services Agreement between Vertex Advisory Group and TechFlow Inc.',
    instructions: 'Identify contradictions between these contracts in a portfolio.',
    clauses: [
      { id: 'clause_01', title: 'Scope of Services', text: 'Consultant shall provide strategic technology consulting services including system architecture review, cloud migration planning, security audits, and digital transformation advisory. All deliverables shall be provided in accordance with the Statement of Work attached as Exhibit A.' },
      { id: 'clause_02', title: 'Compensation', text: 'Client shall pay Consultant at the rate of $450 per hour for all services rendered. Invoices shall be submitted monthly and payment shall be due within Net 30 days of invoice date. Late payments shall accrue interest at 1.5% per month.' },
      { id: 'clause_03', title: 'Intellectual Property Assignment', text: 'All work product, deliverables, inventions, and discoveries created by Consultant in the course of performing services under this Agreement shall be considered "work made for hire" and shall be the exclusive property of Client.' },
      { id: 'clause_04', title: 'Confidentiality', text: 'Consultant shall maintain the confidentiality of all Client information encountered during the engagement. Confidentiality obligations shall survive for a period of two (2) years following termination of this Agreement.' },
      { id: 'clause_05', title: 'Non-Compete', text: 'During the term of this Agreement and for eighteen (18) months thereafter, Consultant shall not provide similar consulting services to any direct competitor of Client within the same geographic market.' },
      { id: 'clause_06', title: 'Indemnification', text: 'Consultant shall indemnify and hold harmless Client from any claims arising from Consultant\'s negligence or willful misconduct. There shall be no cap on Consultant\'s indemnification obligations relating to intellectual property infringement.' },
      { id: 'clause_07', title: 'Liability Cap', text: 'Consultant\'s total liability under this Agreement shall not exceed the total fees paid to Consultant during the preceding six (6) months. This limitation applies to all causes of action, including indemnification claims.' },
    ]
  }
];

export const DEMO_FINDINGS = [
  {
    clause_a_id: 'CONTRACT_2::clause_03',
    clause_b_id: 'CONTRACT_2::clause_05',
    explanation: 'Clause 03 (Data Ownership) explicitly states Provider shall NOT access, use, analyze, or monetize Client Data for any purpose other than providing the Service. However, Clause 05 (Data Analytics License) grants Provider a license to analyze Client Data for ML training, benchmarks, and research — purposes directly forbidden by Clause 03.',
    contradiction_type: 'scope',
    severity: 'high'
  },
  {
    clause_a_id: 'CONTRACT_2::clause_06',
    clause_b_id: 'CONTRACT_2::clause_07',
    explanation: 'Clause 06 allows either party to terminate with only 30 days notice at any time. Clause 07 requires 90 days notice for non-renewal, implying the contract cannot be exited with shorter notice. These timelines are directly incompatible.',
    contradiction_type: 'termination_renewal',
    severity: 'high'
  },
  {
    clause_a_id: 'CONTRACT_3::clause_06',
    clause_b_id: 'CONTRACT_3::clause_07',
    explanation: 'Clause 06 states "no cap on indemnification obligations relating to IP infringement." Clause 07 caps total liability at 6 months of fees and explicitly says this limitation "applies to all causes of action, including indemnification claims." These are directly contradictory.',
    contradiction_type: 'scope',
    severity: 'high'
  },
  {
    clause_a_id: 'CONTRACT_1::clause_03',
    clause_b_id: 'CONTRACT_3::clause_04',
    explanation: 'The NDA (Contract 1, Clause 03) requires confidentiality obligations to survive for 5 years after disclosure. The Consulting Agreement (Contract 3, Clause 04) limits confidentiality survival to only 2 years post-termination. This creates an inconsistency across the portfolio for the same business relationship.',
    contradiction_type: 'temporal',
    severity: 'medium'
  },
  {
    clause_a_id: 'CONTRACT_1::clause_04',
    clause_b_id: 'CONTRACT_1::clause_02',
    explanation: 'Clause 02 requires "strict confidence" and prohibits disclosure to "any third party." Clause 04 permits disclosure to employees, contractors, and advisors. While Clause 04 is a carve-out, the broad language of Clause 02 creates ambiguity about whether contractors qualify as "third parties."',
    contradiction_type: 'party_obligation',
    severity: 'low'
  },
  {
    clause_a_id: 'CONTRACT_2::clause_04',
    clause_b_id: 'CONTRACT_2::clause_08',
    explanation: 'The SLA (Clause 04) guarantees 99.95% uptime with implied remedies for breach. However, Clause 08 excludes all consequential and indirect damages. If downtime causes business losses, the liability cap may render the SLA guarantee effectively unenforceable.',
    contradiction_type: 'scope',
    severity: 'medium'
  },
  {
    clause_a_id: 'CONTRACT_3::clause_03',
    clause_b_id: 'CONTRACT_3::clause_01',
    explanation: 'Clause 03 assigns all "work product and inventions" to Client as work-for-hire. However, Clause 01 references a Statement of Work in Exhibit A — if the SOW scope is narrowly defined, pre-existing consultant IP used in deliverables creates an ownership conflict.',
    contradiction_type: 'definition',
    severity: 'medium'
  },
  {
    clause_a_id: 'CONTRACT_1::clause_05',
    clause_b_id: 'CONTRACT_2::clause_03',
    explanation: 'The NDA requires return or destruction of all confidential information within 30 days of termination. The SaaS Agreement states Client Data remains Client property with no similar return timeline from Provider. Cross-contract data handling obligations are inconsistent.',
    contradiction_type: 'party_obligation',
    severity: 'low'
  }
];

// 12-month risk trend data
export const DEMO_RISK_TREND = [
  { month: 'Apr 2025', score: 22, contracts: 1, contradictions: 0 },
  { month: 'May 2025', score: 28, contracts: 1, contradictions: 1 },
  { month: 'Jun 2025', score: 35, contracts: 2, contradictions: 2 },
  { month: 'Jul 2025', score: 42, contracts: 2, contradictions: 3 },
  { month: 'Aug 2025', score: 38, contracts: 2, contradictions: 2 },
  { month: 'Sep 2025', score: 55, contracts: 3, contradictions: 5 },
  { month: 'Oct 2025', score: 62, contracts: 3, contradictions: 6 },
  { month: 'Nov 2025', score: 58, contracts: 3, contradictions: 5 },
  { month: 'Dec 2025', score: 68, contracts: 3, contradictions: 7 },
  { month: 'Jan 2026', score: 72, contracts: 3, contradictions: 8 },
  { month: 'Feb 2026', score: 65, contracts: 3, contradictions: 7 },
  { month: 'Mar 2026', score: 74, contracts: 3, contradictions: 8 },
];

export function buildClauseAnalysis(contracts, findings) {
  const clauseMap = {};
  
  contracts.forEach(contract => {
    contract.clauses.forEach(clause => {
      const fullId = `${contract.id}::${clause.id}`;
      clauseMap[fullId] = {
        fullId,
        clauseId: clause.id,
        title: clause.title,
        text: clause.text,
        contractName: contract.name,
        contractId: contract.id,
        contradictions: [],
        riskScore: 0,
        riskLevel: 'safe',
      };
    });
  });

  findings.forEach(finding => {
    const a = clauseMap[finding.clause_a_id];
    const b = clauseMap[finding.clause_b_id];
    const sevScore = finding.severity === 'high' ? 3 : finding.severity === 'medium' ? 2 : 1;

    if (a) {
      a.contradictions.push({
        withClause: finding.clause_b_id,
        withTitle: b?.title || 'Unknown',
        withContract: b?.contractName || 'Unknown',
        type: finding.contradiction_type,
        severity: finding.severity,
        explanation: finding.explanation,
      });
      a.riskScore += sevScore;
    }
    if (b) {
      b.contradictions.push({
        withClause: finding.clause_a_id,
        withTitle: a?.title || 'Unknown',
        withContract: a?.contractName || 'Unknown',
        type: finding.contradiction_type,
        severity: finding.severity,
        explanation: finding.explanation,
      });
      b.riskScore += sevScore;
    }
  });

  // Assign risk levels
  Object.values(clauseMap).forEach(clause => {
    if (clause.riskScore >= 3) clause.riskLevel = 'high';
    else if (clause.riskScore >= 1) clause.riskLevel = 'medium';
    else clause.riskLevel = 'safe';
  });

  return Object.values(clauseMap).sort((a, b) => b.riskScore - a.riskScore);
}
